# Base configs
baseurl: "http://massimiani.art"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Artwork by Scarlett Ann Massimiani"
subtitle: "See the world through my eyes!"
author: "Scarlett Ann Massimiani"
header:
 title: "Artwork"
 subtitle: "by Scarlett Ann Massimiani"
footer:
 name: "Hey there, my name is Scarlett"
 bio: "I love drawing and making art. Drawing is my favorite thing to do. Art is like my best friend."
 github: ""
web_design: "SAM"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
